## Numpy Exercise Questions

- Create a New environment and install numpy in it
- Check the version of numpy using pip freeze and __version__

In [ ]:
conda create -n numpyexercise_env python=3.10  

In [2]:
!pip install numpy

In [3]:
!pip freeze

numpy==2.2.6


In [4]:
import numpy as np
print("numpy version:", np.__version__)

numpy version: 2.1.3


### element wise addition

In [7]:
import numpy as np
x = np.array([[1,2,3],
             [4,5,6]], dtype=np.float64)
y = np.array([[10,11,12],
              [13,14,15]], dtype=np.float64)

print(x + y)
print(np.add(x,y))

[[11. 13. 15.]
 [17. 19. 21.]]
[[11. 13. 15.]
 [17. 19. 21.]]


### Multiply matrix with scaler 2

In [8]:
import numpy as np
x = np.array([[1,2,3],
             [4,5,6]])

print( x*2)

[[ 2  4  6]
 [ 8 10 12]]


### Identity matrix of 4*4

In [11]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Construct 1D array and reshape it to 3D array 3*3 shape

In [20]:
import numpy as np
data = np.array([0,1,2,3,4,5,6, 7, 8])
data.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
import numpy as np
data = np.array([
    [[0, 1, 2],
     [3, 4, 5],
     [6, 7, 8]],
    
    [[9, 10, 11],
     [12, 13, 14],
     [15, 16, 17]],
    
    [[18, 19, 20],
     [21, 22, 23],
     [24, 25, 26]]
])
data.reshape(9,3)

### convert numpy array from float to int

In [25]:
import numpy as np
f_array = np.array([[2.5, 3.8, 1.5],
                    [4.7, 2.9, 1.56]])
int_array = f_array.astype(int)
print(int_array)

[[2 3 1]
 [4 2 1]]


### to boolean numpy array

In [28]:
import numpy as np
bin_array = np.array([[1, 0, 0],
                      [1, 1, 1],
                      [0, 0, 0]])
bool_array = f_array.astype(bool)
print(bool_array)

[[ True  True  True]
 [ True  True  True]]


## Horizontally stack array


In [30]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[7,8,9],
              [10,11,12]])
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Sequence of number from 0-100 with gap 2

In [31]:
import numpy as np
seq = np.arange(0,100,2)
print(seq)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [32]:
import numpy as np
seq = np.arange(0,102,2)
print(seq)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


Write a NumPy program that creates a large 1D array using np.random.rand and write a function to calculate the sum of its elements using a for loop. Then, optimize it using NumPy's built-in functions.

In [33]:
import numpy as np
array = np.random.rand(1000000)
sum= np.sum(array)
print(sum)

500382.1885391308


From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match [1,2,3,4,5] and [1,3,2,4,5]

In [36]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 3, 2, 4, 5])
indexes_match = np.where(a == b)
print("match indixes:",indexes_match)

match indixes: (array([0, 3, 4]),)


Output a sequence of equally gapped 5 numbers in the range 0 to 100 Output: [  0.  25.  50.  75. 100.]

In [40]:
import numpy as np
seq = np.arange(0,100,5)
print(seq)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [39]:
#Using np.linspace
import numpy as np
seq = np.linspace(0,100,5)
print(seq)

[  0.  25.  50.  75. 100.]


Output a matrix (numpy array) of dimension 2-by-3 with each and every value equal to 5



In [43]:
a = np.full((2,3),5)
print(a)

[[5 5 5]
 [5 5 5]]


Output a 5-by-5 array of random integers between 0 and 10

In [44]:
e = np.random.random((5,5))
print(e)

[[0.95030948 0.20596334 0.35584564 0.63850747 0.65900434]
 [0.23875231 0.03223858 0.60320828 0.99576913 0.57649411]
 [0.65339406 0.482367   0.15532231 0.60235759 0.52321343]
 [0.60657596 0.28091094 0.14493827 0.45475115 0.10983784]
 [0.71015118 0.82289204 0.71004917 0.56597573 0.9624869 ]]


In [54]:
import numpy as np
e = np.random.randint(0,10, size=(5,5))
print(e)

[[5 2 8 2 5]
 [2 9 2 4 4]
 [2 8 5 1 8]
 [2 2 8 2 6]
 [5 5 9 0 9]]


## DOT product

In [55]:
import numpy as np
x= np.array([[1,2],[2,3]])
y= np.array([[4,5],[6,7]])

#Inner product
print(x.dot(y))
print(np.dot(x,y))

[[16 19]
 [26 31]]
[[16 19]
 [26 31]]


In [56]:
import numpy as np
x= np.array([[1,2,3],[4,5,6],[7,8,9]])
y= np.array([[2,3,4],[5,6,7],[8,9,10]])

#Inner product
print(x.dot(y))
print(np.dot(x,y))

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]
[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


construct a 2X3 random matrix and transpose it

In [57]:
ary = np.array([2,3])
ary.T

array([2, 3])

In [59]:
import numpy as np
random_matrix = np.random.rand(2, 3)
transposed_matrix = random_matrix.T
print(transposed_matrix)

[[0.91226875 0.57040184]
 [0.68210279 0.54610259]
 [0.39363828 0.08961061]]


# calculate std for flatten (whole std)
# calculate std along axis 0 and 1 also

In [60]:
import numpy as np
matrix = np.array([
    [2, 2, 2, 2, 2],
    [15, 6, 27, 8, 2],
    [23, 2, 54, 1, 2],
    [11, 44, 34, 7, 2],
])
whole_std = np.std(matrix)
print(whole_std)

15.3668474320532


In [61]:
import numpy as np
matrix = np.array([
    [2, 2, 2, 2, 2],
    [15, 6, 27, 8, 2],
    [23, 2, 54, 1, 2],
    [11, 44, 34, 7, 2],
])
whole_std = np.std(matrix, axis = 0)
print(whole_std)

[ 7.56224173 17.68473918 18.59267329  3.04138127  0.        ]


In [62]:
import numpy as np
matrix = np.array([
    [2, 2, 2, 2, 2],
    [15, 6, 27, 8, 2],
    [23, 2, 54, 1, 2],
    [11, 44, 34, 7, 2],
])
whole_std = np.std(matrix, axis = 1)
print(whole_std)

[ 0.          8.7772433  20.53874388 16.40243884]


## Use case of inverse matrix

In [ ]:
import numpy as np
a = np.array([
    [6, 4, 2],
    [1, -2, 8],
    [1, 5, 7]
])
inv_matrix=np.linalg.inv(a)
print(inv_matrix)


Load an Image using PIL and convert to numpy array.

In [ ]:
from PIL import Image
import numpy as np
image = Image.open('"C:\Users\ACER\Documents\ViberDownloads\0-02-03-06d6c24f5198a5ecff230fd3d0344d352f69f267ab17334cb2fba7a244eb9848_100e1aead4776547.jpg"')
image_array = np.array(image)


convert dictionary {0: 0, 1: 1, 2: 8, 3: 27,
                4: 64, 5: 125, 6: 216}
to array

In [2]:
d = {0: 0, 1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216}
arr = [d[key] for key in sorted(d)]
print(arr)

[0, 1, 8, 27, 64, 125, 216]


solve the following equatio
3x+y-2z=9,
2x-y+z=3,
x+2y+3z=12

In [1]:
import numpy as np

A = np.array([[3, 1, -2],
              [2, -1, 1],
              [1, 2, 3]])

B = np.array([9, 3, 12])

values = np.linalg.solve(A, B)
print(values)



[2.6 3.2 1. ]


### 3*3*3 array with random values and flatten to 1D array

In [5]:
import numpy as np
threed_array = np.random.rand(3, 3, 3)
flattened_array = threed_array.flatten()
print(flattened_array)


[0.14136269 0.74890732 0.48329828 0.36917197 0.81304352 0.53625585
 0.26346844 0.85501571 0.24426662 0.79820824 0.50503124 0.29136269
 0.027298   0.1993054  0.58206615 0.62776053 0.64926159 0.22537509
 0.10965985 0.83690651 0.88103814 0.30593207 0.3849404  0.56463787
 0.57740059 0.96122164 0.61956601]


Write a NumPy program to create a 3x3 array with random values and calculate the pairwise Euclidean distance between each pair of rows.

In [ ]:
import numpy as np
from scipy.spatial.distance import cdist

array = np.random.rand(3, 3)
print("Original array:", array)

distances = cdist(array, array, metric='euclidean')
print("Pairwise Euclidean distances:", distances)


In [ ]:
df.head()